---
- name: Create VMs
  hosts: localhost
  roles:
    - role: stackhpc.libvirt-vm
      libvirt_vms:
        - state: present
          name: 'vm2'
          memory_mb: 1024
          vcpus: 1
          volumes:
            - type: 'file'
              format: 'qcow2'
              dev: '/home1/vms/vm1.qocw2'
          interfaces:
            - type: 'bridge'
              source:
                dev: 'bridge0'
