---
- name: Create VMs
  hosts: localhost
  vars:
    vmname: vm1
    diskfile: /home1/vms/vm1.qocw2
  roles:
    - role: stackhpc.libvirt-vm
      libvirt_vms:
        - state: present
          name: '{{ vmname }}'
          memory_mb: 64000
          vcpus: 20
          volumes:
            - type: 'file'
              format: 'qcow2'
              dev: '{{ diskfile }}'
          interfaces:
            - type: 'bridge'
              source:
                dev: 'bridge0'
