---
- hosts: localhost
  vars:
    user: www-data
    worker_processes: 2
    pid: /run/nginx.pid
    worker_connections: 768
  tasks:
  - name: demo msg
    debug: 
      msg: "hello world"
  - name: Sleep for 300 seconds and continue with play
    ansible.builtin.wait_for:
    timeout: 300
 
