---
- name: Auto Heal Demo
  hosts: all 
  tasks:    

    - name: Sleep for 300 seconds and continue with play
      ansible.builtin.wait_for:
      timeout: 300      
      
    - name: Template a file to /etc/file.conf
      ansible.builtin.template:
        src: foo.j2
        dest: /etc/neha/foo.conf
      ignore_errors: yes
      

    - name: install the Apache package
      yum:
        name: httpd
        state: present



