---
- name: Auto Heal Demo
  hosts: localhost
  tasks:    

    - name: Template a file to /etc/file.conf
      ansible.builtin.debug:
        msg: "the value of neha.txt is {{lookup('ansible.builtin.file', '/etc/neha/neha.txt') }}"
      
    - name: Template a file to /etc/file.conf
      ansible.builtin.template:
        src: foo.j2
        dest: /etc/neha/foo.conf
      ignore_errors: yes



